// Regenerates ../Data/Tactyks.lua from Tactyks' M+ Ability Tracking Sheet.
// Used with Tactyks' permission, in exchange for credit (see ../README.md).
//
// Usage (Node 18+):  npm run tactyks

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const outFile = join(dirname(fileURLToPath(import.meta.url)), "..", "Data", "Tactyks.lua");

// One sheet per season, newest first; each maps sheet tab -> MDT dungeon index.
const SHEETS = [
  {
    season: "Midnight Season 2",
    id: "1gI8-pZVc5LluzupXtsuNOT6Q7LMTu-rD3v2IJhewakY",
    tabs: {
      "Altar of Fangs": 164,
      "Blinding Vale": 162,
      "Den of Nalorakk": 161,
      "Murder Row": 160,
      "Voidscar Arena": 163,
      "Temple": 20,
      "Kings Rest": 17,
      "Ruby Life Pools": 42,
    },
  },
  {
    season: "Midnight Season 1",
    id: "11pOj8w823fjBJqnOWTCA9vwL8_TVJF-kWFCK6WGJ7Jk",
    tabs: {
      "Magisters Terrace": 153,
      "Maisara Caverns": 154,
      "Nexus-Point": 155,
      "Windrunner Spire": 152,
      "Algeth'ar": 45,
      "Seat": 11,
      "Skyreach": 151,
      "Pit": 150,
    },
  },
];

// Columns that become tags. An "x" becomes the category itself; any other
// value becomes "Category: value" (e.g. "Debuff: Magic", "Frontal: Locks").
// "Important" goes first so it stands out.
const TAG_COLUMNS = [
  "Important", "Interrupt", "Party Dam", "Avoid", "Buff", "Debuff", "Frontal",
  "Tank Buster", "Stop", "Add Spawn", "CC Effect", "Special",
];

function parseCsv(text) {
  const rows = [];
  let row = [], field = "", quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (c !== "\r") field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const luaString = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ").trim()}"`;

async function readTab(sheetId, tab) {
  const url = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${tab}: HTTP ${res.status}`);
  return parseCsv(await res.text());
}

// Trash and bosses sit under separate header rows ("Mob"/"Boss" + "Ability")
// with slightly different columns, so the column map is rebuilt at each one.
function abilitiesOf(rows) {
  const abilities = [];
  let columns = null, mob = null, isBoss = false;
  for (const row of rows) {
    const cells = row.map((c) => c.trim());
    if ((cells[0] === "Mob" || cells[0] === "Boss") && cells[1] === "Ability") {
      columns = Object.fromEntries(cells.map((name, i) => [name, i]).filter(([name]) => name));
      isBoss = cells[0] === "Boss";
      mob = null;
      continue;
    }
    if (!columns) continue;
    const at = (name) => (columns[name] !== undefined ? cells[columns[name]] ?? "" : "");
    if (at("Mob") || at("Boss")) mob = at("Mob") || at("Boss");
    const spellId = Number(at("Ability Link").match(/spell=(\d+)/)?.[1]);
    if (!at("Ability") || !spellId) continue;

    const tags = [];
    for (const category of TAG_COLUMNS) {
      const value = at(category);
      if (!value) continue;
      tags.push(value.toLowerCase() === "x" ? category : `${category}: ${value}`);
    }
    abilities.push({
      mob, isBoss, spellId,
      name: at("Ability"),
      tags,
      note: at("Notes"),
      important: at("Important").toLowerCase() === "x",
    });
  }
  return abilities;
}

const today = new Date().toISOString().slice(0, 10);
const lines = [
  "-- Ability tags, notes and important picks by Tactyks, used with his permission.",
  `-- Generated by tools/fetch-tactyks.mjs from his M+ Ability Tracking Sheets on ${today}:`,
  ...SHEETS.map((s) => `--   ${s.season}: https://docs.google.com/spreadsheets/d/${s.id}`),
  "-- Not covered by this add-on's MIT license.",
  "local _, NPI = ...",
  "NPI.Data.RegisterAbilityData({",
  '  name = "Tactyks",',
  "  dungeons = {",
];
let total = 0, important = 0;
for (const sheet of SHEETS) for (const [tab, dungeonIndex] of Object.entries(sheet.tabs)) {
  const abilities = abilitiesOf(await readTab(sheet.id, tab));
  if (abilities.length === 0) throw new Error(`${sheet.season} / ${tab}: no abilities found (renamed tab or new layout?)`);
  lines.push(`    [${dungeonIndex}] = { -- ${sheet.season}: ${tab}`);
  for (const a of abilities) {
    const fields = [`spellId = ${a.spellId}`, `tags = { ${a.tags.map(luaString).join(", ")} }`];
    if (a.note) fields.push(`note = ${luaString(a.note)}`);
    // The boss whose section lists it: the add-on defaults these to important
    // for that boss and its adds.
    if (a.isBoss) fields.push(`boss = ${luaString(a.mob)}`);
    if (a.important) fields.push("important = true");
    lines.push(`      { ${fields.join(", ")} }, -- ${a.mob}${a.isBoss ? " (boss)" : ""}: ${a.name}`);
  }
  lines.push("    },");
  total += abilities.length;
  important += abilities.filter((a) => a.important).length;
  console.log(`${tab} [${dungeonIndex}]: ${abilities.length} abilities, ${abilities.filter((a) => a.important).length} important`);
}
lines.push("  },", "})", "");
writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`\nWrote ${outFile}: ${total} abilities, ${important} important`);
